name: sp_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  cloud_firestore: ^4.17.3
  table_calendar: ^3.0.0
  shared_preferences: ^2.2.2
  firebase_storage: ^11.2.2
  image_picker: ^0.8.4+4
  uuid: ^3.0.6
  firebase_app_check: ^0.2.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
